// qhull_all.cpp — auto-generated: includes libqhullcpp translation units
// This file must live in src/ (top-level) so R will compile it.
#include "libqhullcpp/Coordinates.cpp"
#include "libqhullcpp/PointCoordinates.cpp"
#include "libqhullcpp/Qhull.cpp"
#include "libqhullcpp/QhullFacet.cpp"
#include "libqhullcpp/QhullFacetList.cpp"
#include "libqhullcpp/QhullFacetSet.cpp"
#include "libqhullcpp/QhullHyperplane.cpp"
#include "libqhullcpp/QhullPoint.cpp"
#include "libqhullcpp/QhullPoints.cpp"
#include "libqhullcpp/QhullPointSet.cpp"
#include "libqhullcpp/QhullQh.cpp"
#include "libqhullcpp/QhullRidge.cpp"
#include "libqhullcpp/QhullSet.cpp"
#include "libqhullcpp/QhullStat.cpp"
#include "libqhullcpp/QhullUser.cpp"
#include "libqhullcpp/QhullVertex.cpp"
#include "libqhullcpp/QhullVertexSet.cpp"
#include "libqhullcpp/RboxPoints.cpp"
#include "libqhullcpp/RoadError.cpp"
#include "libqhullcpp/RoadLogEvent.cpp"
#include "libqhullcpp/usermem_r-cpp.cpp"
