# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create a FOCuS Changepoint Detector
#'
#' Creates an online (sequential) changepoint detector object that provides
#' a step-by-step interface to the FOCuS algorithm. Each call to
#' \code{\link{detector_update}()} adds new data, and \code{\link{get_statistics}()} computes
#' the current test statistic and detection result.
#'
#' @param type Character string specifying detector type. One of:
#'   \itemize{
#'     \item \code{"univariate"}: Two-sided univariate detection
#'     \item \code{"univariate_one_sided"}: One-sided univariate detection
#'     \item \code{"multivariate"}: Multivariate detection with projections
#'     \item \code{"npfocus"}: Nonparametric detection (NP-FOCuS). See details.
#'     \item \code{"arp"}: AutoRegressive Process detection. Requires \code{rho} parameter.
#'   }
#' @param dim_indexes List of integer vectors specifying projection index sets
#'   for high-dimensional multivariate detectors (not required for data with
#'   at most 5 dimensions). Each element is a vector of 0-based column indices.
#'   Default is \code{NULL}.
#' @param quantiles Numeric vector of quantiles for nonparametric
#'   (\code{"npfocus"}) detectors. Required when \code{type = "npfocus"}.
#'   Default is \code{NULL}.
#' @param pruning_mult Integer. Candidate pruning multiplier parameter.
#'   Default is 2.
#' @param pruning_offset Integer. Candidate pruning offset parameter.
#'   Default is 1.
#' @param side Character string. For one-sided detectors, either \code{"right"}
#'   (detects increases) or \code{"left"} (detects decreases). Default is
#'   \code{"right"}.
#' @param anomaly_intensity Numeric scalar. Anomaly intensity threshold for
#'   pruning candidates. Only candidates with sufficient signal magnitude are
#'   retained. Default is \code{NULL} (disabled).
#' @param rho Numeric vector. AR coefficients for AutoRegressive Process (ARP)
#'   detectors. Required when \code{type = "arp"}. Default is \code{NULL}.
#' @param mu0_arp Numeric scalar. Pre-change mean for ARP detectors (optional).
#'   When provided, enables more efficient pruning by filtering candidates based on
#'   the known pre-change parameter. Only used when \code{type = "arp"}.
#'   Default is \code{NULL}.
#'
#' @return An object of class \code{"focus_detector"}: an external pointer to
#'   the state of the C++ detector, which is updated in place. It should be
#'   passed to the other detector functions, such as
#'   \code{\link{detector_update}()} and \code{\link{get_statistics}()}.
#'   \code{print} and \code{summary} methods are available, see
#'   \code{\link{focus-methods}}. As external pointers, detectors cannot be
#'   saved and restored across \R sessions.
#'
#' @details
#' The detector maintains sufficient statistics internally and uses pruning
#' to efficiently track candidate changepoints. The \code{pruning_mult} and
#' \code{pruning_offset} parameters control the pruning strategy.
#'
#' \strong{AutoRegressive Process (ARP).}
#' When \code{type = "arp"}, the \code{rho} parameter must be provided as a numeric
#' vector of AR coefficients (lag-1, lag-2, ..., lag-p). The detector then computes
#' statistics optimal for detecting changepoints in AR(p) processes. Use
#' \code{get_statistics(family = "arp")} to retrieve the test statistics.
#' The optional \code{mu0_arp} parameter specifies the pre-change mean and is tied
#' to the pruning logic: if provided, it enables more efficient pruning by allowing
#' the algorithm to filter candidates based on the known pre-change parameter.
#'
#' \strong{High-dimensional multivariate detectors.}
#' For high-dimensional multivariate detection, computing the full convex hull
#' is prohibitive, as the expected number of candidates grows as
#' \eqn{\log(n)^p}{log(n)^p}, where \eqn{n} is the number of observations and
#' \eqn{p} the number of dimensions. The set of candidate changepoints can then
#' be approximated by computing the hull on lower-dimensional projections:
#' \code{dim_indexes} specifies which dimensions to use for each projection.
#' Use \code{\link{generate_projection_indexes}()} to generate systematic
#' projection sets.
#'
#' \strong{NPFOCuS.}
#' For non-parametric detection, create the detector with
#' \code{detector_create(type = "npfocus", quantiles = ...)} and compute the
#' statistics with \code{get_statistics(family = "npfocus")}. No other family
#' can be used with this detector type.
#'
#' @examples
#' # Univariate detector
#' det <- detector_create(type = "univariate")
#' det <- detector_update(det, 0.5)
#' det <- detector_update(det, 1.2)
#' det
#' r <- get_statistics(det, family = "gaussian")
#' r
#'
#' ## Online (sequential) example
#' # Generate data with a changepoint
#' set.seed(123)
#' Y <- c(rnorm(500, mean = 0), rnorm(500, mean = 1))
#' det <- detector_create(type = "univariate")
#' stat_trace <- numeric(length(Y))
#' threshold <- 20
#' for (i in seq_along(Y)) {
#'   detector_update(det, Y[i])
#'   r <- get_statistics(det, family = "gaussian")
#'   stat_trace[i] <- r$stat
#'   if (!is.null(r$stat) && r$stat > threshold) {
#'     cat("Online detection at", i, "estimate tau =", r$changepoint, "\n")
#'     plot(stat_trace[1:i], type = "l", ylab = "Test Statistic", xlab = "Time")
#'     break
#'   }
#' }
#'
#' # Multivariate detector with projections
#' dim_indexes <- list(c(0,1), c(1,2), c(0,2))  # 0-based indices
#' det_mv <- detector_create(type = "multivariate", dim_indexes = dim_indexes)
#' detector_update(det_mv, c(0.5, 1.2, -0.3))
#'
#' # Nonparametric detector
#' quants <- qnorm(c(0.25, 0.5, 0.75))
#' det_np <- detector_create(type = "npfocus", quantiles = quants)
#'
#' # One-sided univariate detector
#' det_one_sided <- detector_create(type = "univariate_one_sided", side = "left")
#'
#' @export
detector_create <- function(type, dim_indexes = NULL, quantiles = NULL, pruning_mult = 2L, pruning_offset = 1L, side = "right", anomaly_intensity = NULL, rho = NULL, mu0_arp = NULL) {
    .Call(`_focus_detector_create`, type, dim_indexes, quantiles, pruning_mult, pruning_offset, side, anomaly_intensity, rho, mu0_arp)
}

#' Update a Detector with New Observations
#'
#' Adds a new observation to the detector's internal state, updates the
#' sufficient statistics and prunes the set of candidate changepoints.
#'
#' @param det_ptr A \code{"focus_detector"} object created by
#'   \code{\link{detector_create}()}.
#' @param y Numeric vector with the new observation. For univariate detectors,
#'   this should be a scalar (length-1 vector). For multivariate detectors,
#'   this should be a vector matching the number of dimensions.
#' @param lambda Numeric scalar. Weight of the new observation: the internal
#'   time counter is incremented by \code{lambda} rather than by one, which
#'   allows for a non-constant background rate (e.g., observation-specific
#'   exposures). Default is \code{1.0}, i.e., one observation per update.
#'
#' @return
#' The same \code{"focus_detector"} object that was passed in. The detector is
#' updated \emph{in place} (no copy is made), so the return value is provided
#' only for convenience, for example to chain calls with the native pipe
#' operator, as in
#' \code{det |> detector_update(y) |> get_statistics(family = "gaussian")}.
#'
#' @examples
#' # Univariate example
#' det <- detector_create(type = "univariate")
#' detector_update(det, 0.5)
#' detector_update(det, 1.2)
#'
#' # Multivariate example
#' det_mv <- detector_create(type = "multivariate")
#' detector_update(det_mv, c(0.5, 1.2, -0.3))
#'
#' ## Online (sequential) example
#' # Generate data with a changepoint
#' set.seed(123)
#' Y <- c(rnorm(500, mean = 0), rnorm(500, mean = 1))
#' det <- detector_create(type = "univariate")
#' stat_trace <- numeric(length(Y))
#' threshold <- 20
#' for (i in seq_along(Y)) {
#'   detector_update(det, Y[i])
#'   r <- get_statistics(det, family = "gaussian")
#'   stat_trace[i] <- r$stat
#'   if (!is.null(r$stat) && r$stat > threshold) {
#'     cat("Online detection at", i, "estimate tau =", r$changepoint, "\n")
#'     plot(stat_trace[1:i], type = "l", ylab = "Test Statistic", xlab = "Time")
#'     break
#'   }
#' }
#'
#'
#' @export
detector_update <- function(det_ptr, y, lambda = 1.0) {
    .Call(`_focus_detector_update`, det_ptr, y, lambda)
}

#' Compute the Current Changepoint Statistics
#'
#' Computes the current changepoint test statistic and detection result based
#' on all observations processed so far.
#'
#' @param det_ptr A \code{"focus_detector"} object created by
#'   \code{\link{detector_create}()}.
#' @param family Character string specifying the distribution family:
#'   \itemize{
#'     \item \code{"gaussian"}: Gaussian (normal) distribution
#'     \item \code{"poisson"}: Poisson distribution
#'     \item \code{"bernoulli"}: Bernoulli (binary) distribution
#'     \item \code{"gamma"}: Gamma distribution (requires \code{shape} parameter)
#'     \item \code{"npfocus"}: Nonparametric detection (see details)
#'     \item \code{"arp"}: AutoRegressive Process detection (requires detector created with \code{type = "arp"})
#'   }
#' @param theta0 Numeric vector specifying the null hypothesis parameter.
#'   For univariate detectors: scalar (length-1 vector).
#'   For multivariate detectors: vector matching the number of dimensions.
#'   Default is \code{NULL}.
#' @param shape Numeric scalar. Shape parameter for gamma distribution.
#'   Required and must be positive when \code{family = "gamma"}.
#'   Default is \code{NULL}.
#'
#' @return An object of class \code{"focus_statistics"}, with a \code{print}
#'   method (see \code{\link{focus-methods}}): a list with components
#'   \item{stopping_time}{Numeric. Current time index (number of observations
#'     processed).}
#'   \item{changepoint}{Numeric or \code{NULL}. Estimated changepoint location,
#'     i.e., the index of the last observation before the change, or
#'     \code{NULL} if no estimate is available.}
#'   \item{stat}{Numeric scalar or vector, or \code{NULL} if no candidate is
#'     available yet. The test statistic: a scalar for all families except
#'     \code{"npfocus"}, which returns the sum and the maximum of the
#'     statistics over the quantiles.}
#'   The family is stored in the attribute \code{"family"}.
#'
#' @details
#' The function computes a log-likelihood ratio test statistic comparing the
#' null hypothesis (no change) against the alternative (a change at the optimal
#' location). The statistic is typically compared against a threshold to
#' determine if a changepoint should be declared.
#'
#' \strong{Gamma family.}
#' When \code{family = "gamma"} a positive \code{shape} parameter must
#' be provided; otherwise an error is raised. Passing \code{shape} for a
#' non-gamma family raises a warning and the parameter is ignored.
#'
#' \strong{NPFOCuS.}
#' For non-parametric detection, the detector must be created with
#' \code{detector_create(type = "npfocus", quantiles = ...)}. NPFOCuS returns
#' two statistics (sum and maximum over the quantiles) as a vector; in the
#' offline interface, \code{stat} is a matrix with two columns.
#'
#' \strong{AutoRegressive Process (ARP).}
#' For ARP detection, use \code{family = "arp"} with a detector created via
#' \code{detector_create(type = "arp", rho = ...)}. The AR coefficients and the
#' (optional) pre-change mean \code{mu0_arp} are set at detector creation, so
#' \code{theta0} is ignored (with a warning) for this family.
#'
#' @examples
#'
#' ## Online (sequential) example
#' # Generate data with a changepoint
#' set.seed(123)
#' Y <- c(rnorm(500, mean = 0), rnorm(500, mean = 1))
#' det <- detector_create(type = "univariate")
#' stat_trace <- numeric(length(Y))
#' threshold <- 20
#' for (i in seq_along(Y)) {
#'   detector_update(det, Y[i])
#'   r <- get_statistics(det, family = "gaussian")
#'   stat_trace[i] <- r$stat
#'   if (!is.null(r$stat) && r$stat > threshold) {
#'     cat("Online detection at", i, "estimate tau =", r$changepoint, "\n")
#'     plot(stat_trace[1:i], type = "l", ylab = "Test Statistic", xlab = "Time")
#'     break
#'   }
#' }
#'
#' ## Note that multiple models can be tested simultaneously on the same detector
#' # as the statistics is independent of the detector state.
#' # For example, testing both Gaussian and Poisson costs
#' set.seed(2024)
#' # Generate Poisson count data with a rate change
#' Y_counts <- c(rpois(500, lambda = 10), rpois(500, lambda = 15))
#' # Compute full trajectories for comparison
#' det2 <- detector_create(type = "univariate")
#' stat_gaussian <- numeric(length(Y_counts))
#' stat_poisson <- numeric(length(Y_counts))
#'
#' for (i in seq_along(Y_counts)) {
#'   detector_update(det2, Y_counts[i])
#'   stat_gaussian[i] <- get_statistics(det2, family = "gaussian")$stat
#'   stat_poisson[i] <- get_statistics(det2, family = "poisson", theta0 = 10)$stat
#' }
#'
#' # Plot comparison
#' oldpar <- par(mfrow = c(1, 2))
#' plot(stat_gaussian, type = "l", main = "Gaussian Statistic on Poisson Data",
#'      xlab = "Time", ylab = "Statistic", lwd = 2, col = "blue")
#' abline(v = 500, col = "green", lty = 3, lwd = 2)
#'
#' plot(stat_poisson, type = "l", main = "Poisson Statistic on Poisson Data",
#'      xlab = "Time", ylab = "Statistic", lwd = 2, col = "red")
#' abline(v = 500, col = "green", lty = 3, lwd = 2)
#' par(oldpar)
#'
#'
#' @export
get_statistics <- function(det_ptr, family, theta0 = NULL, shape = NULL) {
    .Call(`_focus_get_statistics`, det_ptr, family, theta0, shape)
}

.detector_cands_len <- function(det_ptr) {
    .Call(`_focus_detector_cands_len`, det_ptr)
}

.detector_info_n <- function(det_ptr) {
    .Call(`_focus_detector_info_n`, det_ptr)
}

.detector_info_sn <- function(det_ptr) {
    .Call(`_focus_detector_info_sn`, det_ptr)
}

.detector_candidates <- function(det_ptr) {
    .Call(`_focus_detector_candidates`, det_ptr)
}

#' Generate Projection Index Sets
#'
#' Generates projection index sets for high-dimensional multivariate detectors
#' using circular combinations.
#'
#' @param d Integer. Total number of dimensions.
#' @param p Integer. Projection subset size (number of dimensions per projection).
#'
#' @return An object of class \code{"focus_projections"}: a list of integer
#'   vectors, each holding the 0-based column indices of one projection, with
#'   the number of dimensions and the projection size stored in the attributes
#'   \code{"d"} and \code{"p"}. It can be passed directly as the
#'   \code{dim_indexes} argument of \code{\link{detector_create}()} and
#'   \code{\link{focus_offline}()}. A \code{print} method shows one projection
#'   per row, subsetting with \code{[} (e.g., \code{head()}) keeps the class,
#'   and \code{as.matrix()} returns the indices as a matrix with one row per
#'   projection; see \code{\link{focus-methods}}.
#'
#' @details
#' This function generates systematic projection sets for use with multivariate
#' detectors. The circular combination approach ensures good coverage of the
#' dimensional space while keeping the number of projections manageable.
#'
#' @examples
#' # Generate 2-dimensional projections from 5 dimensions
#' proj <- generate_projection_indexes(d = 5, p = 2)
#' proj
#' as.matrix(proj)
#'
#' # Use with multivariate detector
#' det <- detector_create(type = "multivariate", dim_indexes = proj)
#' detector_update(det, c(0.5, 1.2, -0.3, 0.8, 0.1))
#'
#' # Offline comparison of the full detector and approximation
#' set.seed(42)
#' d <- 6
#'
#' # Create data: changepoint at t=1000
#' Y_multi <- rbind(
#'     matrix(rnorm(1000 * d, mean = -1, 1), ncol = d),
#'     matrix(rnorm(500 * d, mean = 1.2), ncol = d)
#' )
#'
#' # Full multivariate detection
#' system.time(
#' res_multi <- focus_offline(Y_multi, threshold = Inf,
#'                            type = "multivariate", family = "gaussian")
#' )
#'
#' # Low-dimensional projection approximation
#' dim_indexes <- generate_projection_indexes(6, 2)
#' system.time(
#' res_multi_approx <- focus_offline(Y_multi, threshold = Inf,
#'                                   type = "multivariate", family = "gaussian",
#'                                   dim_indexes = dim_indexes)
#' )
#'
#' # Verify similarity
#' all.equal(res_multi$stat, res_multi_approx$stat)
#'
#' @export
generate_projection_indexes <- function(d, p) {
    .Call(`_focus_generate_projection_indexes`, d, p)
}

#' @name focus_offline
#' @title Run a FOCuS Detector in Offline Batch Mode
#'
#' @description
#' Processes all data at once and returns detection results and trajectories.
#' This is the most efficient way to run changepoint detection when all data
#' is available upfront.
#'
#' @param Y Numeric vector or matrix. Data array. For univariate detection,
#'   a numeric vector. For multivariate detection, a matrix with observations
#'   in rows and dimensions in columns.
#' @param threshold Numeric scalar or vector. Detection threshold(s). Can be:
#'   \itemize{
#'     \item A scalar: applied to all test statistics (default behavior for most cost functions)
#'     \item A vector: length must match the number of test statistics (for example, np-focus
#'       returns both the sum and max statistics, so threshold should be length 2).
#'     \item \code{Inf}: no thresholding (returns all statistics)
#'   }
#' @param type Character string specifying detector type. See
#'   \code{\link{detector_create}()} for options. Defaults to \code{"univariate"}.
#' @param family Character string specifying distribution family. See
#'   \code{\link{get_statistics}()} for options. Defaults to \code{"gaussian"}.
#' @param theta0 Numeric vector. Null hypothesis parameter. Default is \code{NULL}.
#' @param dim_indexes List of integer vectors. Projection index sets for
#'   multivariate detectors. Default is \code{NULL}.
#' @param quantiles Numeric vector. Quantiles for nonparametric detectors.
#'   Default is \code{NULL}.
#' @param pruning_mult Integer. Pruning multiplier parameter. Default is 2.
#' @param pruning_offset Integer. Pruning offset parameter. Default is 1.
#' @param side Character string. For one-sided detectors: \code{"right"} or
#'   \code{"left"}. Default is \code{"right"}.
#' @param shape Numeric scalar. Shape parameter for gamma distribution.
#'   Default is \code{NULL}.
#' @param anomaly_intensity Numeric scalar. Anomaly intensity threshold for
#'   pruning candidates. Only candidates with sufficient signal magnitude are
#'   retained. Default is \code{NULL} (disabled).
#' @param rho Numeric vector. AR coefficients for AutoRegressive Process (ARP)
#'   detectors. Required when \code{type = "arp"}. Default is \code{NULL}.
#' @param mu0_arp Numeric scalar. Pre-change mean for ARP detectors (optional).
#'   Only used when \code{type = "arp"}.
#'   Default is \code{NULL}.
#'
#' @return An object of class \code{"focus_offline"}, with \code{print},
#'   \code{summary} and \code{plot} methods (see \code{\link{focus-methods}}):
#'   a list with components
#'   \item{stat}{Numeric matrix. Test statistics over time (n_obs × n_stats).
#'     Each row corresponds to one time point, each column to one statistic.}
#'   \item{changepoint}{Integer vector. Detected changepoints at each time
#'     point (1-based indices), or NA if no changepoint detected at that time.}
#'   \item{detection_time}{Integer or NULL. Time of first detection (1-based),
#'     or NULL if no detection occurred.}
#'   \item{detected_changepoint}{Integer or NULL. Changepoint location at
#'     detection time (1-based), or NULL if no detection occurred.}
#'   \item{candidates}{Data frame. Final candidate segments (see
#'     \code{detector_candidates()}).}
#'   \item{threshold}{Numeric vector. Threshold(s) used for detection.}
#'   \item{n}{Integer. Number of observations processed.}
#'   \item{type}{Character. Detector type used.}
#'   \item{family}{Character. Distribution family used.}
#'   \item{shape}{Numeric or NULL. Shape parameter (for gamma family).}
#'
#' @details
#' This function runs the complete detection algorithm in C++ for maximum
#' efficiency. It processes observations sequentially and stops at the first
#' detection (when any statistic exceeds its threshold).
#'
#' When more than one statistic is computed (e.g., the sum and maximum
#' statistics of \code{"npfocus"}), a detection occurs when any statistic
#' exceeds its threshold.
#'
#' @examples
#' # Univariate Gaussian detection
#' set.seed(123)
#' Y <- c(rnorm(100, mean = 0), rnorm(100, mean = 2))
#' result <- focus_offline(Y, threshold = 10, type = "univariate",
#'                        family = "gaussian")
#' result
#' summary(result)
#'
#' # Plot the trace of the statistic, the threshold and the detection
#' plot(result)
#'
#' # Plot the data above the trace of the statistic
#' plot(result, data = Y)
#'
#' # Poisson detection
#' Y_poisson <- c(rpois(100, lambda = 2), rpois(100, lambda = 5))
#' result_poisson <- focus_offline(Y_poisson, threshold = 10,
#'                                 type = "univariate",
#'                                 family = "poisson")
#'
#' @export
focus_offline <- function(Y, threshold, type = "univariate", family = "gaussian", theta0 = NULL, dim_indexes = NULL, quantiles = NULL, pruning_mult = 2L, pruning_offset = 1L, side = "right", shape = NULL, anomaly_intensity = NULL, rho = NULL, mu0_arp = NULL) {
    .Call(`_focus_focus_offline`, Y, threshold, type, family, theta0, dim_indexes, quantiles, pruning_mult, pruning_offset, side, shape, anomaly_intensity, rho, mu0_arp)
}

